# SPDX-FileCopyrightText: 2023 Michael Pöhn <michael.poehn@fsfe.org>
# SPDX-License-Identifier: CC0-1.0

release-build:
  only:
    - /^v[0-9]+\..+$/
  image: node:bookworm-slim
  script:
    - yarnpkg global add gulp-cli
    - yarnpkg install
    - yarnpkg run build
    - yarnpkg run zip
  artifacts:
    paths:
      - ./dist.zip

reuse:
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
